# question 1

In [4]:
import pandas as pd 
time = {
    'date_time':  ['2024-06-01 14:30', '2024-06-02 09:15', '2024-06-03 20:45'] 
}
df = pd.DataFrame(time)
print(df)
df['date_time'] = pd.to_datetime(df['date_time'])
df

          date_time
0  2024-06-01 14:30
1  2024-06-02 09:15
2  2024-06-03 20:45

            date_time
0 2024-06-01 14:30:00
1 2024-06-02 09:15:00
2 2024-06-03 20:45:00

# question 2

In [25]:
df = pd.read_csv("flipkart_order_history_10k.csv")
df['order_date'] = pd.to_datetime(df['order_date'])
# year, month, and weekday
df['year'] = df['order_date'].dt.year
df['date'] = df['order_date'].dt.date
df['day'] = df['order_date'].dt.day_name()
df.head(10)

,order_id,customer_id,customer_name,customer_email,phone_number,shipping_address,city,state,pincode,order_date,category,product_name,quantity,price_per_unit,total_amount,payment_method,order_status,year,date,day
0,OD085083213843,CUST646649,Diya Iyer,diya.iyer322@example.com,9349924125,"Flat 34, Society D, Mumbai",Mumbai,Maharashtra,398590,2023-09-19 12:29:13,Health,Protein Powder,1,1899,1899,Cash on Delivery,Delivered,2023,2023-09-19,Tuesday
1,OD724927212540,CUST285696,Rahul Joshi,rahul.joshi331@example.com,9446787943,"Flat 153, Society A, Hyderabad",Hyderabad,Telangana,392528,2023-09-19 13:18:05,Fashion,Running Shoes,1,1599,1599,UPI,Delivered,2023,2023-09-19,Tuesday
2,OD980049147782,CUST470615,Sneha Joshi,sneha.joshi993@example.com,9500721043,"Flat 83, Society B, Kolkata",Kolkata,West Bengal,529426,2023-09-19 18:54:01,Fashion,T-Shirt,2,499,998,Cash on Delivery,Delivered,2023,2023-09-19,Tuesday
3,OD327680433089,CUST381463,Rahul Singh,rahul.singh397@example.com,9633488951,"Flat 91, Society A, Bengaluru",Bengaluru,Karnataka,137284,2023-09-19 20:25:36,Home,Bedsheet,1,799,799,UPI,Returned,2023,2023-09-19,Tuesday
4,OD071214024808,CUST762514,Anjali Reddy,anjali.reddy151@example.com,9104746614,"Flat 419, Society B, Kolkata",Kolkata,West Bengal,653114,2023-09-19 21:45:26,Fashion,Jeans,1,1299,1299,Debit Card,Delivered,2023,2023-09-19,Tuesday
5,OD646404312084,CUST894289,Anjali Bose,anjali.bose504@example.com,9017807404,"Flat 168, Society B, Lucknow",Lucknow,Uttar Pradesh,168356,2023-09-20 01:40:26,Fashion,Jeans,2,1299,2598,UPI,Delivered,2023,2023-09-20,Wednesday
6,OD093362869783,CUST156198,Karan Joshi,karan.joshi643@example.com,9112345810,"Flat 90, Society A, Delhi",Delhi,Delhi,228557,2023-09-20 02:12:47,Fashion,Jeans,1,1299,1299,UPI,Delivered,2023,2023-09-20,Wednesday
7,OD947589127086,CUST300068,Rohit Patel,rohit.patel185@example.com,9985121479,"Flat 116, Society D, Mumbai",Mumbai,Maharashtra,141371,2023-09-20 02:36:31,Books,Novel,1,299,299,UPI,Delivered,2023,2023-09-20,Wednesday
8,OD087457957618,CUST974853,Vikram Kumar,vikram.kumar281@example.com,9504491311,"Flat 28, Society B, Chennai",Chennai,Tamil Nadu,788952,2023-09-20 02:50:20,Home Appliances,Blender,2,2250,4500,Cash on Delivery,Delivered,2023,2023-09-20,Wednesday
9,OD165984558512,CUST983733,Rahul Bose,rahul.bose265@example.com,9514590440,"Flat 241, Society D, Pune",Pune,Maharashtra,754031,2023-09-20 03:14:43,Electronics,Smartwatch,1,2499,2499,Credit Card,Shipped,2023,2023-09-20,Wednesday

# question 3

In [26]:
df.set_index('order_date', inplace=True)
weekly_orders = df.resample('W').size()

In [31]:
weekly_orders.head()

order_date
2023-09-24    55
2023-10-01    76
2023-10-08    72
2023-10-15    55
2023-10-22    65
Freq: W-SUN, dtype: int64

# question 4

In [43]:
df = pd.read_csv('instagram_posts_dataset.csv')
print(df.head())
df['posted_at_utc'] = pd.to_datetime(df['posted_at_utc']).dt.tz_localize('UTC')
df['posted_at_ist'] = df['posted_at_utc'].dt.tz_convert('Asia/Kolkata')
df.head()

         post_id          username        posted_at_utc post_type  likes  \
0  IG_9500693818    foodie_anjali3  2024-09-18 13:01:26     Image    640
1  IG_3335827017   foodie_anjali94  2024-09-18 16:57:07     Image     40
2  IG_3814846751      kavita_art22  2024-09-18 21:40:16     Image     90
3  IG_5010310829  suresh_fitness25  2024-09-19 01:44:12      Reel     66
4  IG_5191636893     rahul_rocks97  2024-09-19 14:15:01     Image     14

   comments  shares  saves             location  \
0        38      62    147      Bali, Indonesia
1         4       1      4    Jaipur, Rajasthan
2         5       6      2           Goa, India
3        11       3     15  Mumbai, Maharashtra
4         1       0      2    Pune, Maharashtra

                                           hashtags
0                 #travel #photooftheday #instagood
1  #foodie #photography #photooftheday #music #love
2  #lifestyle #photooftheday #nature #foodie #viral
3                 #music #instagood #fashion #viral
4                                 #music #instagood

,post_id,username,posted_at_utc,post_type,likes,comments,shares,saves,location,hashtags,posted_at_ist
0,IG_9500693818,foodie_anjali3,2024-09-18 13:01:26+00:00,Image,640,38,62,147,"Bali, Indonesia",#travel #photooftheday #instagood,2024-09-18 18:31:26+05:30
1,IG_3335827017,foodie_anjali94,2024-09-18 16:57:07+00:00,Image,40,4,1,4,"Jaipur, Rajasthan",#foodie #photography #photooftheday #music #love,2024-09-18 22:27:07+05:30
2,IG_3814846751,kavita_art22,2024-09-18 21:40:16+00:00,Image,90,5,6,2,"Goa, India",#lifestyle #photooftheday #nature #foodie #viral,2024-09-19 03:10:16+05:30
3,IG_5010310829,suresh_fitness25,2024-09-19 01:44:12+00:00,Reel,66,11,3,15,"Mumbai, Maharashtra",#music #instagood #fashion #viral,2024-09-19 07:14:12+05:30
4,IG_5191636893,rahul_rocks97,2024-09-19 14:15:01+00:00,Image,14,1,0,2,"Pune, Maharashtra",#music #instagood,2024-09-19 19:45:01+05:30

# question 5

In [ ]:
df['is_weekend'] = df['posted_at_ist'].dt.day_of_week >= 5

In [49]:
df.head(20)

,post_id,username,posted_at_utc,post_type,likes,comments,shares,saves,location,hashtags,posted_at_ist,is_weekend
0,IG_9500693818,foodie_anjali3,2024-09-18 13:01:26+00:00,Image,640,38,62,147,"Bali, Indonesia",#travel #photooftheday #instagood,2024-09-18 18:31:26+05:30,False
1,IG_3335827017,foodie_anjali94,2024-09-18 16:57:07+00:00,Image,40,4,1,4,"Jaipur, Rajasthan",#foodie #photography #photooftheday #music #love,2024-09-18 22:27:07+05:30,False
2,IG_3814846751,kavita_art22,2024-09-18 21:40:16+00:00,Image,90,5,6,2,"Goa, India",#lifestyle #photooftheday #nature #foodie #viral,2024-09-19 03:10:16+05:30,False
3,IG_5010310829,suresh_fitness25,2024-09-19 01:44:12+00:00,Reel,66,11,3,15,"Mumbai, Maharashtra",#music #instagood #fashion #viral,2024-09-19 07:14:12+05:30,False
4,IG_5191636893,rahul_rocks97,2024-09-19 14:15:01+00:00,Image,14,1,0,2,"Pune, Maharashtra",#music #instagood,2024-09-19 19:45:01+05:30,False
5,IG_3444524633,sneha_style16,2024-09-19 15:48:30+00:00,Reel,41,1,2,4,"Ahmedabad, Gujarat",#music #photooftheday #nature #trending #fashion,2024-09-19 21:18:30+05:30,False
6,IG_3542685804,sneha_style32,2024-09-19 20:50:25+00:00,Video,214,24,16,19,"Ahmedabad, Gujarat",#travel #love #art #nature #trending,2024-09-20 02:20:25+05:30,False
7,IG_2037042083,foodie_anjali78,2024-09-20 10:49:54+00:00,Reel,155,4,4,33,NaN,#nature #instagood #foodie #viral #trending #t...,2024-09-20 16:19:54+05:30,False
8,IG_9675556102,the_wanderer86,2024-09-20 11:44:08+00:00,Carousel,584,55,27,93,"Dubai, UAE",#lifestyle #fashion #art #nature,2024-09-20 17:14:08+05:30,False
9,IG_6540495628,kavita_art11,2024-09-20 12:01:44+00:00,Video,400,8,31,14,"Jaipur, Rajasthan",#fashion #love #foodie #photography #photoofth...,2024-09-20 17:31:44+05:30,False
10,IG_1200955967,rahul_rocks73,2024-09-20 14:07:25+00:00,Reel,102,1,9,12,"Goa, India",#travel #love #music #nature #photooftheday #v...,2024-09-20 19:37:25+05:30,False
11,IG_4277731353,suresh_fitness92,2024-09-20 18:59:29+00:00,Image,82,6,6,19,"Jaipur, Rajasthan",#foodie #instagood #music #photography #viral,2024-09-21 00:29:29+05:30,True
12,IG_5878713585,foodie_anjali17,2024-09-21 00:39:22+00:00,Carousel,738,70,52,109,"Jaipur, Rajasthan",#lifestyle #foodie #music #art #trending #phot...,2024-09-21 06:09:22+05:30,True
13,IG_8955773659,priya_daily6,2024-09-21 07:32:16+00:00,Image,170,10,5,10,NaN,#nature #lifestyle #photooftheday #love #viral...,2024-09-21 13:02:16+05:30,True
14,IG_7926187672,the_wanderer71,2024-09-21 09:27:23+00:00,Image,186,14,14,7,"Paris, France",#love #instagood,2024-09-21 14:57:23+05:30,True
15,IG_1479713087,sneha_style68,2024-09-21 13:17:34+00:00,Image,203,25,8,16,NaN,#viral #photography #art,2024-09-21 18:47:34+05:30,True
16,IG_9283647269,suresh_fitness63,2024-09-21 15:30:01+00:00,Image,38,7,3,5,"Goa, India",#photography #art,2024-09-21 21:00:01+05:30,True
17,IG_9659436591,the_wanderer96,2024-09-22 07:23:58+00:00,Reel,292,56,12,61,"Dubai, UAE",#music #fitness #photooftheday,2024-09-22 12:53:58+05:30,True
18,IG_0798891304,style_icon78,2024-09-22 12:23:52+00:00,Carousel,77,7,2,6,NaN,#instagood #love #fitness #art #lifestyle #tre...,2024-09-22 17:53:52+05:30,True
19,IG_6554454764,amit_travels36,2024-09-22 13:41:43+00:00,Image,292,5,28,22,"Dubai, UAE",#art #photography #photooftheday,2024-09-22 19:11:43+05:30,True