# question 1

In [21]:
import pandas as pd 
df = pd.read_csv("zomato_orders.csv")
df[df.duplicated(["Restaurant_Name","Order_Date"])]

     Restaurant_Name  Order_Date             Item_Name  Order_Value_INR
23     Sushi Rollers  2026-08-04       Chicken Biryani           407.91
31     Noodle Corner  2026-07-17       Chicken Biryani           304.97
46   Dim Sum Delight  2026-06-20          Mutton Kebab           367.78
74    Sweet Cravings  2026-09-18      Margherita Pizza           996.07
76     Sushi Rollers  2026-07-12          Caesar Salad           864.53
..               ...         ...                   ...              ...
991   Sweet Cravings  2026-08-20                 Tacos           859.87
992      Bake & Cake  2026-07-10  Paneer Butter Masala          1124.17
994   Pizza Paradise  2026-08-14      Margherita Pizza           501.49
997     Wok This Way  2026-06-20  Paneer Butter Masala           932.11
999      Taco Fiesta  2026-06-28          Mutton Kebab           759.34

[249 rows x 4 columns]

# question 2

In [31]:
df = pd.read_csv("flipkart_10k_reviews.csv")
dc = df['Review_Text'].value_counts()
print(dc[dc>1].head(3))

Review_Text
Awesome delivery speed.                  703
Excellent customer support.              700
Defective item received, returned it.    697
Name: count, dtype: int64

# question 3

In [39]:
df = pd.read_csv("spotify_playlists.csv")
print(df)
print(df.drop_duplicates())

        playlist_name    creator_name
0       Acoustic Wave      MC Johnson
1         Metal Study     Riley Jones
2       Classical Mix    Jordan Smith
3          Indie Flow  Riley Williams
4     Essential Blues     DJ Martinez
...               ...             ...
9995   Indie Classics   Skyler Garcia
9996         Deep Pop    Lil Martinez
9997        Focus Mix     Casey Beats
9998       R&B Energy    Avery Master
9999       Techno Jam  Riley Williams

[10000 rows x 2 columns]
           playlist_name     creator_name
0          Acoustic Wave       MC Johnson
1            Metal Study      Riley Jones
2          Classical Mix     Jordan Smith
3             Indie Flow   Riley Williams
4        Essential Blues      DJ Martinez
...                  ...              ...
9964     Electronic Soul   Taylor Johnson
9966     Country Anthems    Skyler Master
9977  Ultimate Classical    Music Johnson
9979         Classic Mix  Jordan Martinez
9996            Deep Pop     Lil Martinez

[3619 rows x 2 columns]

# question 4

In [40]:
insta_data = {'Username': ['insta_queen', 'photo_guy', 'insta-queen', 'instaqueen', 'travel_bug']}
df = pd.DataFrame(insta_data)
df['Username'] = df['Username'].replace(['insta_queen', 'insta-queen'], 'instaqueen')
print(df)

     Username
0  instaqueen
1   photo_guy
2  instaqueen
3  instaqueen
4  travel_bug

# question 5

In [46]:
paytm_data = {'Payment_Status': [' Yes ', 'no', ' Y', 'N ', 'yes', ' No ', 'y', 'n']}
df = pd.DataFrame(paytm_data)
print(df)
df['Payment_Status'] = df['Payment_Status'].str.strip().str.lower().map({'yes':1,'y':1,'no':0,'n':0})
df

  Payment_Status
0           Yes
1             no
2              Y
3             N
4            yes
5            No
6              y
7              n

   Payment_Status
0               1
1               0
2               1
3               0
4               1
5               0
6               1
7               0